### ISSUE TITLE
Examples need updating and curation

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/examples-lingua-franca#27]
I just did a random sample of some programs in C examples repo, and most examples I chose failed:

* AnytimePrime.lf  doesn't compile.
* SensorSimulator.lf compiles and then segfaults.
* Rhythm.lf segfaults.

Is it really too early in the development process to be actually developing applications?
Or are we not paying enough attention to backward compatibility?
Note that we can't expect outside users to commit a regression test for every application they develop.

**Comment by edwardalee** [comment]
Fixed the segfaults in SensorSimulator.lf and Rhythm.lf.  The distributed examples in Rhythm no longer work because of the restructured fed-gen folder structure. Looking for a fix now.

Also, all the examples need to be reformatted to get rid of warnings about now deprecated parameter overrides.

**Comment by edwardalee** [comment]
Fixed, reorganized, and documented the AnytimePrime.lf example.

**Comment by lhstrh** [comment]
See https://github.com/lf-lang/examples-lingua-franca/issues/1.

**Comment by lhstrh** [comment]
A complete summary of broken examples can be found here: https://github.com/lf-lang/examples-lingua-franca/actions/runs/5194568881 (note that this does not include examples located in `experimental` or `failing` directories).

**Comment by lhstrh** [comment]
Remaining failures to be found [here](https://github.com/lf-lang/examples-lingua-franca/actions/runs/5195892227).

**Comment by cmnrd** [comment]
I created a new issue to better keep track of individual tasks https://github.com/lf-lang/examples-lingua-franca/issues/34. I close this issue in favor of the new one.
